In [2]:
list = [3,4,5,6,7]
list

[3, 4, 5, 6, 7]

In [3]:
list+ 10

TypeError: can only concatenate list (not "int") to list

In [5]:
import numpy 
ndarray = numpy.array([4,65,7,7878])
ndarray


array([   4,   65,    7, 7878])

In [6]:
type(ndarray)


numpy.ndarray

In [7]:
ndarray+1000

array([1004, 1065, 1007, 8878])

In [8]:
import numpy as np
ndarray = np.array(  [4,65,7,78,98]  )
print(ndarray)

type(ndarray)
ndarray + 1000


[ 4 65  7 78 98]


array([1004, 1065, 1007, 1078, 1098])

In [9]:
np.__version__

'1.18.5'

In [10]:
ndarray.dtype

dtype('int32')

In [15]:
import numpy as np
ndarray = np.array(  [1,2,3,4,5,6,7,8.2,9]  )
print(ndarray)

[1.  2.  3.  4.  5.  6.  7.  8.2 9. ]


In [14]:
ndarray.dtype

dtype('int32')

In [16]:
import numpy as np
ndarray = np.array(  [1,2,3,4,5,6,7,8.2,9]  )
print(ndarray)

[1.  2.  3.  4.  5.  6.  7.  8.2 9. ]


In [17]:
ndarray.dtype

dtype('float64')

In [19]:
import numpy as np
ndarray = np.array(  [1,2,3,4,5,6,7,8.2,9] ,dtype = 'int16' )
print(ndarray)

[1 2 3 4 5 6 7 8 9]


In [20]:
ndarray.dtype

dtype('int16')

In [2]:
import numpy as np
mylist = np.array([
                    [
                        [0,1,2],
                        [3.9,4,5],
                        [3,4,5]
                    ],
                    [
                        [0,1,2],
                        [3.9,4,5],
                        [3,4,5]
                    ],[
                        [0,1,2],
                        [3.9,4,5],
                        [3,4,5]
                    ],[
                        [0,1,2],
                        [3.9,4,5],
                        [3,4,5]
                    ]
] )
#print(mylist)

print(mylist.ndim )
print(mylist.shape )
#print(mylist.dtype)
#print(mylist.flags)


3
(4, 3, 3)


In [3]:
import numpy as np
arr = np.zeros(10)  
print(arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
type(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

<class 'numpy.ndarray'>
1
(10,)
float64


In [7]:
arr = np.zeros([20,5])  # i1= 8 bit ....i2 = 16 bit
arr.dtype                                      
arr



array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
arr = np.zeros([20,5])  # i1= 8 bit ....i2 = 16 bit
arr.dtype                                      
arr
arr = np.zeros([20,5], dtype= 'int64')  # i1= 8 bit ....i2 = 16 bit
print(arr.size)                                     
arr


100


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [14]:
arr = np.zeros([20,5])  # i1= 8 bit ....i2 = 16 bit
arr.dtype                                      
arr
arr = np.zeros([20,5], dtype= 'i4')  # i1= 8 bit ....i2 = 16 bit
print(arr.size)                                     
arr
print(arr.dtype)


100
int32


In [21]:
arr = np.ones([20,5])  # i1= 8 bit ....i2 = 16 bit
print(arr)
arr.dtype                                      
arr
arr = np.zeros([20,5], dtype= 'i4')  # i1= 8 bit ....i2 = 16 bit
print(arr.size)                                     
arr
print(arr.dtype)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
100
int32


In [3]:
import numpy as np
np.random.random(3)
a=np.full([8,3],212)
a

array([[212, 212, 212],
       [212, 212, 212],
       [212, 212, 212],
       [212, 212, 212],
       [212, 212, 212],
       [212, 212, 212],
       [212, 212, 212],
       [212, 212, 212]])

In [4]:
a = np.ones((8,6), dtype= 'i2')
print(a)
a.dtype
a = np.full([8,4], 10)
a
a = np.full([8,4], 255)
a


[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


array([[255, 255, 255, 255],
       [255, 255, 255, 255],
       [255, 255, 255, 255],
       [255, 255, 255, 255],
       [255, 255, 255, 255],
       [255, 255, 255, 255],
       [255, 255, 255, 255],
       [255, 255, 255, 255]])

In [6]:
np.random.random([ 2,4,  3])


array([[[0.34629522, 0.89422621, 0.30646856],
        [0.6407186 , 0.79052292, 0.20891844],
        [0.44871127, 0.64780107, 0.5349137 ],
        [0.60690447, 0.14190819, 0.70478866]],

       [[0.23906739, 0.62411496, 0.60926787],
        [0.25228812, 0.10762715, 0.99007235],
        [0.68949161, 0.1198121 , 0.83886449],
        [0.18406629, 0.16976681, 0.66222657]]])

In [8]:

np.random.randint(7)


6

In [9]:

np.random.randint(180,190)


185

In [10]:

np.random.randint(180,201,4)


array([199, 184, 192, 180])

In [11]:
#                STRAT, END, NO.
np.random.randint(674, 998, 10)
#                STRAT, END, NO.
np.random.randint(674, 695, [8,3])


array([[690, 692, 684],
       [686, 690, 690],
       [675, 674, 686],
       [683, 681, 677],
       [689, 674, 678],
       [677, 682, 679],
       [694, 689, 692],
       [684, 683, 688]])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [14]:
np.arange(10.67, 20.77, 0.2)


array([10.67, 10.87, 11.07, 11.27, 11.47, 11.67, 11.87, 12.07, 12.27,
       12.47, 12.67, 12.87, 13.07, 13.27, 13.47, 13.67, 13.87, 14.07,
       14.27, 14.47, 14.67, 14.87, 15.07, 15.27, 15.47, 15.67, 15.87,
       16.07, 16.27, 16.47, 16.67, 16.87, 17.07, 17.27, 17.47, 17.67,
       17.87, 18.07, 18.27, 18.47, 18.67, 18.87, 19.07, 19.27, 19.47,
       19.67, 19.87, 20.07, 20.27, 20.47, 20.67])

In [15]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [17]:
np.linspace(1,100,10, retstep=True)


(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [18]:
np.linspace(1,500,200, retstep=True,dtype= 'int')

(array([  1,   3,   6,   8,  11,  13,  16,  18,  21,  23,  26,  28,  31,
         33,  36,  38,  41,  43,  46,  48,  51,  53,  56,  58,  61,  63,
         66,  68,  71,  73,  76,  78,  81,  83,  86,  88,  91,  93,  96,
         98, 101, 103, 106, 108, 111, 113, 116, 118, 121, 123, 126, 128,
        131, 133, 136, 138, 141, 143, 146, 148, 151, 153, 156, 158, 161,
        163, 166, 169, 171, 174, 176, 179, 181, 184, 186, 189, 191, 194,
        196, 199, 201, 204, 206, 209, 211, 214, 216, 219, 221, 224, 226,
        229, 231, 234, 236, 239, 241, 244, 246, 249, 251, 254, 256, 259,
        261, 264, 266, 269, 271, 274, 276, 279, 281, 284, 286, 289, 291,
        294, 296, 299, 301, 304, 306, 309, 311, 314, 316, 319, 321, 324,
        326, 329, 331, 334, 337, 339, 342, 344, 347, 349, 352, 354, 357,
        359, 362, 364, 367, 369, 372, 374, 377, 379, 382, 384, 387, 389,
        392, 394, 397, 399, 402, 404, 407, 409, 412, 414, 417, 419, 422,
        424, 427, 429, 432, 434, 437, 439, 442, 444

In [1]:
import numpy as np
arr = np.array(  [1,2,3,4,5,6,7,8] )
print(arr)

arr.reshape(  (4,2) )
#arr.reshape(   (2,4)  )


[1 2 3 4 5 6 7 8]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [2]:
From Sourabh Taneja to Everyone:  08:48 PM
import numpy as np
arr = np.array(  [1,2,3,4,5,6,7,8] )
print(arr)

arr.reshape(  (4,2) )
#arr.reshape(   (2,4)  )
arr.reshape((6,4))
arr.reshape((2,4), order='C')


SyntaxError: invalid syntax (<ipython-input-2-bb0c45df1e4e>, line 1)

In [8]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
arr.flatten(order='F')



(2, 3)
2


array([1, 4, 2, 5, 3, 6])

In [9]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr)

arr.flatten()
#arr.flatten(order='C')
arr.flatten(order='F')


(2, 3)
2
[[1 2 3]
 [4 5 6]]


array([1, 4, 2, 5, 3, 6])

In [10]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
import numpy as np
arr = np.array([-1, 2, 0, 4,45])
print(arr[1])          # indexing, out of bound if index not available
print(arr[2 : 5])      # Slicing


2
[ 0  4 45]


In [14]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
arr[2,1,]


0.0

In [18]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
arr[1:4]
arr[1:3,0:4]


array([[ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ]])

In [19]:
# [ START : END] --> SLICING
# [ ROW, COLUMN]

arr[ 1 :3  , 0 : 4 ]
#   [1,2] , [0,1,2,3]
#   ROWS. , COLUMNS


array([[ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ]])

In [20]:
arr[0:2,2:4]

array([[0., 4.],
       [6., 0.]])

In [28]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
#arr[0][1]
#arr[[2,3],[2,3]]
#arr[[0,1,2,3],[3,0,1,2]]
arr[arr>0]
arr [  arr > 4 ]
arr[arr > 0]
arr[arr == 0]
arr != 0



array([[ True,  True, False,  True],
       [ True,  True,  True, False],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [31]:
import numpy as np
l = [23,45,45,34,34,7565]
l = np.array(l)
#np.mean(l)
np.max(l)
np.min(l)


23

In [36]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
#arr[1][2]
#arr[1,2]
#arr + 1
#arr ** 2
arr *= 1   # arr = arr + 1
arr * 5
#arr / 8


array([[ -5. ,  10. ,   0. ,  20. ],
       [ 20. ,  -2.5,  30. ,   0. ],
       [ 13. ,   0. ,  35. ,  40. ],
       [ 15. , -35. ,  20. ,  10. ]])

In [40]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

#arr.sum()
arr.sum(axis=0)
arr.sum(axis=1)
arr.min(axis=0)
arr.min(axis=1)
arr.max(axis=0)
#arr.max(axis=1)


array([4., 2., 7., 8.])

In [41]:
a = np.array([[1,2],
             [3,4]])

b = np.array([[5,6],
             [7,8]])
a+b

array([[ 6,  8],
       [10, 12]])

In [42]:
a-b

array([[-4, -4],
       [-4, -4]])

In [43]:
np.sin(arr)
np.cos(arr)
np.tan(arr)
np.exp(arr)


array([[3.67879441e-01, 7.38905610e+00, 1.00000000e+00, 5.45981500e+01],
       [5.45981500e+01, 6.06530660e-01, 4.03428793e+02, 1.00000000e+00],
       [1.34637380e+01, 1.00000000e+00, 1.09663316e+03, 2.98095799e+03],
       [2.00855369e+01, 9.11881966e-04, 5.45981500e+01, 7.38905610e+00]])